
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
    EMPLOYEE_NUMBER NUMBER NOT NULL AUTO_INCREMENT,
    LAST_NAME VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    TITLE VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    EMAIL VARCHAR(255),
    HIRE_DATE VARCHAR(255),
    DEPARTMENT_NUMBER NUMBER,
    MANAGER JAVA_OBJECT,
    PRIMARY KEY (EMPLOYEE_NUMBER)
);

DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT(
    DEPARTMENT_NUMBER NUMBER NOT NULL AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(255),
    DEPARTMENT_MANAGER_ID VARCHAR(255),
    PRIMARY KEY (DEPARTMENT_NUMBER)
);

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;

