

DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
    ID INT NOT NULL AUTO_INCREMENT,
    LAST_NAME VARCHAR2(255),
    FIRST_NAME VARCHAR2(255),
    TITLE VARCHAR2(255),
    PHONE_NUMBER VARCHAR2(255),
    EMAIL VARCHAR2(255),
    HIRE_DATE VARCHAR2(255),
    DEPARTMENT_NUMBER INT,
    //MANAGER JAVA_OBJECT,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (
    ID INT NOT NULL AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR2(255),
    DEPARTMENT_MANAGER_ID INT,
    PRIMARY KEY (ID)
);

DROP SEQUENCE IF EXISTS hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;


